### ISSUE TITLE
issue while insalling module

### ISSUE THREAD

**Issue by techloverparveen** [Genaker/reactmagento2#1]
Hi team, I am new in Magento, Just want to know where should I add these files in magento folder structure, Would appreciate if you please let me know in bit detail.

I mean first I need to install Magento then what steps I need to follow to create app using reactjs.

**Comment by dimaportenko** [comment]
Just put `React` dir to the `app/code` and run `php bin/magento setup:upgrade`.

**Comment by techloverparveen** [comment]
> Just put `React` dir to the `app/code` and run `php bin/magento setup:upgrade`.

Thanks for your answer @troublediehard, Would appreciate if you please let me  know that can we also create our extension in Magento2 using any tech-stack (like nodejs) or PHP is must?

**Comment by dimaportenko** [comment]
@techloverparveen not sure what you mean. Magento 2 is basically PHP application.

**Comment by Genaker** [comment]
How it works:

This file compiles React to magento:
https://github.com/Genaker/reactmagento2/blob/master/React/React/webpack.config.js
It uses Magento directory structure to build and deploy React UI  components
It also automatically deploy changes
you don't need to do anything (run static content deploy ), just reload the page,
it also can automatically reload it

**How to use It:**
just copy install/copy this module 

From the extension root (React/React) folder run:

```
npm install
npm start
```
it includes react bundle to require js config file 
after you can use react components in any modules, for now you should put you component to src/ folder index js file 
Add files to another module which will render React component 
layout/
```
<referenceContainer name="product.info.main">
                    <block class="Magento\Framework\View\Element\Template" after="product.info.price" name="product.info.test.options" as="test" template="Module_React::product/view/react.phtml">
                        <arguments>
                            <argument name="view_model" xsi:type="object">Module\React\ViewModel\Catalog\Product\View\Warranty</argument>
                        </arguments>
                    </block>
        </referenceContainer>
```

Add template file:
templates/product/react.phtml
Content:
```
// You also can use x-magento init tag up to you 
require(['react-app', 'jquery'], function (App, jQuery) {
App.init('root');
}
<div id="root-"></div>
```

and that's it 

if you need you can add  json data for you component

```
document.react = {
            "react-data":
            <?php echo $json; ?>,
            "react-block":<?php echo json_encode(["html" => $reactBlock]) ?>,
            "add_tocart_url": '<?= $viewModel->getAddToCartUrl($currentProduct)?>'
        };
```

without any AJAX requests

**Comment by Genaker** [comment]
When you need trigger something in Magento frontend we can easily use jQuery or Vanilla JS (JS without any shitty frameworks)

We can even trigger react state changes or check state values.
`let Warranty = App.init('root');`

if we save React component globally you can read its properties and even invoke react.component functions :)

```
const childBtn = document.getElementById("product-addtocart-button");
childBtn.addEventListener("click", event => {
                    if (Warranty.state.selectedItem === null && (Warranty.state.selected === false)) {
                        document.afterAddToCart = true;
                        jQuery("#product-addtocart-button").off().promise().done(function(){
                        Warranty.togglePopup();
                        });
                    }
```
What do we have there?
Regular magento "Add To Cart" button
`const childBtn = document.getElementById("product-addtocart-button");`
Add new click event to this button

`childBtn.addEventListener("click"...`
Removing all old magento events handlers and adding React component popup function execution on magento click.
```
  jQuery("#product-addtocart-button").off().promise().done(function(){
                        Warranty.togglePopup(); //React function call
                        });
```

We can also check state of react from magneto fronted:
`Warranty.state.selectedItem`
We can even change react component state and trigger component rerenderinf
`Waranty.stateSet({value:true})`
