### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by badi238** [Genaker/reactmagento2#2]
Hi, I am new on this I have installed module and followed your steps everything seems working fine. I have run these commands 

npm install
npm start

it created content in the static folder.

but nothing changed store still behaves like it was working before. How can I see the changes?
when I clicked this URL

http://51.38.87.137:35729

showing this message 

`{"tinylr":"Welcome","version":"1.1.1"}`

my store URL is 

http://51.38.87.137:81/

Can you please help what I am missing or what's the issue? Thanks

**Comment by parag1810** [comment]
Hi,
module installed properly but i need to implement OTP auto read code with magento2, so need to know more that is this module is helpful for my further work and how I implement through it.
I am having reactjs code with me for OTP auto read code.
Having two js files and manifest.json file
I tried by putting these file in app/code/React/React/view/base/web/js

Please let me know this.
Thanks

**Comment by Genaker** [comment]
Tish code doesn't work with manifest.js - manifest
